// @ts-check

/**
 * SigUI core index module for index.
 * @module
 */
export { toOklch, fromOklch } from "./color-space/oklch.js";
export { parseHex, toHex } from "./color-space/srgb.js";
export { clamp, normalizeHue } from "./utils.js";
export {
  lighten,
  darken,
  saturate,
  desaturate,
  shiftHue
} from "./manipulation/adjust.js";
export {
  interpolateColor,
  gradientFill,
  multiGradient
} from "./manipulation/interpolate.js";
export { isInGamut } from "./gamut/check.js";
export { clampToGamut } from "./gamut/clamp.js";
export { deltaEOK } from "./gamut/delta.js";
export { compareRampGamut, comparePaletteGamut } from "./gamut/compare.js";
export { apcaContrast } from "./contrast/apca.js";
export {
  wcag2Contrast,
  meetsWCAG_AA,
  meetsWCAG_AAA
} from "./contrast/wcag2.js";
export {
  bridgeLcToRatio,
  bridgePcaContrast,
  meetsBridgeAA,
  meetsBridgeAAA
} from "./contrast/bridge-pca.js";
export { generateShadeRamp } from "./generation/shade.js";
export { ALL_STOPS, STANDARD_STOPS, EXTENDED_STOPS } from "./generation/targets.js";
export { generatePalette } from "./palette.js";
export { simulateCVD } from "./cvd/simulate.js";
export {
  validateCvdPair,
  validateCategoricalPalette
} from "./cvd/validate.js";
export {
  rampToDTCG,
  paletteToDTCG,
  rolesToDTCG,
  spacingToDTCG,
  typographyToDTCG,
  shadowsToDTCG,
  motionToDTCG,
  themeToDTCG,
  i18nToDTCG,
  iconsToDTCG,
  aspectRatiosToDTCG
} from "./tokens.js";
export {
  generateTypeScale,
  computeLineHeight,
  computeLetterSpacing,
  computeMeasure,
  getFontWeights,
  darkModeAdjustments,
  fluidFontSize,
  remToPx,
  pxToRem,
  longMeasureOffset,
  measureTokens,
  capsLetterSpacing,
  suggestedWeight,
  gradeOffset,
  fluidTypeScale,
  deriveFluidMaxRatio,
  assignSemanticRoles,
  RATIO_BANDS,
  computeBodyFromViewingAngle,
  VIEWING_ANGLE_K,
  DEVICE_PRESETS,
  computeVerticalRhythm,
  computeHeadingSpacing,
  getDyslexiaAdjustments,
  applyDyslexiaLineHeight,
  getFontSizeAdjust,
  FONT_X_HEIGHT_RATIOS,
  needsXHeightNormalization
} from "./typography/index.js";
export {
  generateShadow,
  generateShadowScale,
  adaptShadowForDarkMode,
  generateDarkModeShadow,
  getZIndexScale,
  getZIndex,
  getBorderScale,
  getBorderRadiusScale,
  nestedRadius,
  getSurfaceMaterial,
  getEdgeHighlight,
  getEdgeHighlightDeclaration
} from "./elevation/index.js";
export {
  generateSpacingScale,
  getSpacingValue,
  SEMANTIC_SPACING_TOKENS,
  getMinTouchTarget,
  getTouchTargetSpec,
  computeFittsTime,
  fittsIndexOfDifficulty,
  meetsWCAGTouchTarget,
  computeHitAreaExpansion,
  TOUCH_TARGET_SIZES,
  getDensityMultiplier,
  applyDensity,
  applyDensityClamped,
  composeSpacingScales,
  getContextScaleFactor,
  DENSITY_MULTIPLIERS,
  DENSITY_CSS_VALUES,
  DENSITY_EXEMPT_COMPONENTS,
  CONTEXT_SCALE_FACTORS,
  getBreakpoints,
  getBreakpoint,
  getBreakpointQuery,
  getBreakpointRangeQuery,
  resolveBreakpoint,
  BREAKPOINT_VALUES,
  BREAKPOINT_ORDER,
  getGridConfig,
  getAllGridConfigs,
  computeColumnWidth,
  computeSpanWidth,
  validateGridConfig,
  CONTAINER_BREAKPOINT_VALUES,
  CONTAINER_BREAKPOINT_ORDER,
  getContainerBreakpointQuery,
  getContainerBreakpointRangeQuery,
  getRelationshipSpacing,
  getAllRelationshipSpacings,
  getDefaultSpacing,
  validateProximityHierarchy,
  spacingRelationship,
  relationshipForDepth,
  isInRelationshipRange,
  distributeSpacing,
  constraintsFromRelationships,
  distributeRelationshipSpacing,
  computeDistributionEnergy,
  fluidSpacing,
  fluidSpacingScale,
  computeContentSpacing,
  computeComponentHeight,
  VERTICAL_PADDING_PRESETS,
  opticalSpacingMultiplier,
  opticalSpacingFluid,
  deriveFontSpacingSubset,
  generateFontSpacingSubsets,
  VISUAL_WEIGHTS,
  OPTICAL_ADJUSTMENT_MATRIX,
  getOpticalAdjustment,
  generateOpticalCSS,
  buildTokenMap,
  parseCSSBlocks,
  resolveValueToPx,
  auditProximityHierarchy,
  auditRhythmRegularity,
  auditLineMeasure,
  auditTouchTargets,
  auditAlignmentConsistency,
  auditSpacingClutter,
  auditLayout,
  computeLayoutBalance
} from "./spacing/index.js";
export {
  getDurationScale,
  getScaledDurationScale,
  computeDuration,
  getEasingCurves,
  cubicBezier,
  easingToCss,
  cubicBezierToTuple,
  tupleToCubicBezier,
  getSpringPresets,
  computeSpringDuration,
  springToLinear,
  getReducedMotionAlternative,
  isReducedMotion,
  getAllReducedMotionAlternatives,
  isValidReducedMotionStrategy,
  getTransitionPreset,
  getAllTransitionPresets,
  computeStaggerDelay,
  computeEasedStaggerDelay,
  computeFlipInversion,
  FLIP_THRESHOLD_PX,
  computeVelocity,
  detectSwipe,
  applyDragConstraint,
  elasticDisplacement,
  normalizePath,
  interpolatePath,
  approximatePathLength
} from "./motion/index.js";
export {
  getFocusRingConfig,
  getFocusRingCSS,
  getForcedColorsFocusCSS,
  getScrollPaddingConfig,
  computeScrollPadding,
  getStateLayerConfig,
  getStateLayerOpacity,
  getStateLayerColor,
  getStatePriority,
  getStatePriorityRank,
  resolveDominantState,
  getCursorTokens,
  getCursorValue,
  resolveStateCursor,
  getValidationVisual,
  getValidationTokens,
  needsErrorSummary,
  getLoadingThresholds,
  selectLoadingStrategy,
  getSkeletonConfig,
  getButtonSpinnerConfig,
  getPopoverTransitionConfig,
  getPopoverMode,
  getAIConfig,
  getAIPromptInputConfig,
  getMessageVisual,
  getAIInputState,
  getConfidenceLevel,
  getConfidenceColor
} from "./interactive/index.js";
export { getHapticMappings, triggerHaptic } from "./interactive/index.js";
export {
  RTL_LOCALES,
  isRTLLocale,
  getLocaleDirection,
  SCRIPT_FONT_STACKS,
  SCRIPT_LINE_HEIGHTS,
  SCRIPT_DENSITY_CATEGORIES,
  APCA_SCRIPT_ADJUSTMENTS,
  getScriptForLocale,
  getScriptCategory,
  getLineHeightOffset,
  getAPCAOffset,
  getScriptFontStack,
  LANGUAGE_EXPANSION_RATIOS,
  IBM_EXPANSION_GUIDELINES,
  estimateExpansion,
  pseudoLocalize,
  LOGICAL_PROPERTY_MAP,
  DIRECTIONAL_ICONS,
  generateI18nCSS
} from "./i18n/index.js";
export {
  DEFAULT_PERFORMANCE_BUDGETS,
  getPerformanceBudgets,
  DEFAULT_VITALS,
  DEFAULT_ANIMATION_BUDGET,
  DEFAULT_DOM_BUDGET,
  DEFAULT_IMAGE_BUDGET,
  DEFAULT_FONT_BUDGET,
  DEFAULT_CSS_BUDGET,
  DEFAULT_JS_BUDGET,
  DEFAULT_CI_BUDGET,
  DEFAULT_MONITORING_BUDGET,
  classifyProperty,
  getPropertyClassification,
  isAnimationSafe,
  getCompositorProperties,
  getLayoutTriggeringProperties,
  getPaintTriggeringProperties,
  getAspectRatios,
  getAspectRatio,
  getAspectRatioNames,
  getAspectRatioCSS,
  validateDOMDepth,
  validateComponentNodeCount,
  validatePageNodeCount,
  getListRenderingStrategy,
  estimateRecalcCost,
  getContainmentCSS,
  getDefaultContainment,
  getOverflowContainment,
  getContainmentLevels,
  getContentVisibilityCSS,
  getImageLoadingConfig,
  validateLCPImage,
  getFormatCascade,
  getMandatoryImageAttributes,
  getFontDisplay,
  validateFontSize,
  validateFontPayload,
  validatePreloadCount,
  getFontPreloadRules,
  lintLayoutAnimations,
  lintNoImport,
  lintNoUniversalAnimation,
  lintSelectorSpecificity,
  estimateSpecificity,
  lintCSS
} from "./performance/index.js";
export {
  ICON_SIZES,
  ICON_STROKES,
  STROKE_PROFILES,
  DEFAULT_DARK_MODE_COMPENSATION,
  getIconSize,
  getIconStroke,
  getStrokeProfile,
  getStrokeForSize,
  computeCornerRadius,
  ICON_CATEGORIES,
  ICON_ALIASES,
  CORE_ICON_MANIFEST,
  resolveIconName,
  validateIconName,
  getIconCategory,
  ICONS_THAT_MIRROR,
  ICONS_THAT_DO_NOT_MIRROR,
  shouldMirrorInRTL,
  isFixedDirection,
  DEFAULT_ICON_CONFIG,
  resolveIconConfig,
  validateIconConfig
} from "./icons/index.js";
export {
  computeAlphaEquivalent,
  computeAlphaShadeRamp,
  generateAlphaRamp,
  generateBlackAlphaScale,
  generateWhiteAlphaScale
} from "./alpha/index.js";
export { ALPHA_STOPS } from "./types.js";
export { composePalette } from "./compose.js";
export { computeHarmony, generateFullPalette, deriveSurfaceScale, deriveBrandBackground } from "./harmony/index.js";
export {
  getDefaultAccessibilityConfig,
  getComplianceLevel,
  meetsComplianceLevel,
  ARIA_PATTERNS,
  getAriaPattern,
  getAriaPatternNames,
  KEYBOARD_MAPS,
  getKeyboardMap,
  createShortcutRegistry,
  registerShortcut,
  lookupShortcut,
  validateShortcutModifier,
  ANNOUNCEMENT_PATTERNS,
  getAnnouncementPattern,
  getThrottleConfig,
  FOCUS_RESTORATION_TARGETS,
  getDefaultSkipLinks,
  getFocusableSelector,
  getRouteChangeFocusSelector
} from "./accessibility/index.js";
export {
  classifyDevice,
  deriveCommittedInputMode,
  estimateViewingDistance,
  estimateScreenPpi,
  getDeviceParameters,
  classifyRefreshRate,
  getMinAnimationDuration,
  REFRESH_TIER_MIN_DURATION,
  inferDisplayType,
  getDarkModeWeightOffset,
  resolveGamut,
  DEFAULT_DEVICE_CONTEXT
} from "./device/index.js";
